export const courseData = [
  {
    name: "Learn Core Java",
    description:
      "This course will provide you in depth knowledge of core java and this is the best course and there is high demand for this course.",
    duration: "3 Hour",
    image_url: "ProgLang/java.png",
    link: "https://www.w3schools.com/java/",
    topics: [
      "Java Home",
      "Java Install",
      "Java Syntax",
      "Java Comments",
      "Java Variables",
      "Java Echo/Print",
      "Java Datatype",
      "Java String",
      "Java Numbers",
      "Java Casting",
      "Java Math",
      "Java Constraint",
      "Java Magic Constraint",
      "Java Operators",
      "Java If...Else...Elseif",
      "Java Switch",
      "Java Loops",
      "Java Functions",
      "Java Arrays",
      "Java Superglobals",
      "Java RegEx",
    ],
    created_at: null,
    updated_at: null,
    deleted_at: "2025-11-12T23:24:03.485Z",
  },
  {
    name: "Learn High-Level-Design",
    description:
      "This course will provide you in depth knowledge of Low-Level-Design and this is the best course and there is high demand for this course.",
    duration: "3 Hour",
    image_url: "SystemDesign/hld.png",
    link: "https://www.geeksforgeeks.org/what-is-high-level-design-learn-system-design/",
    topics: [
      "What is High Level Design ",
      "Components of High-Level Design",
      "What is High-Level Design Document?",
      "How HLD is different from LLD",
      "LLD Prerequisite For HLD",
      "How To Design Scalable High-level Design (HLD) Systems",
    ],
    created_at: null,
    updated_at: null,
    deleted_at: "2025-11-12T23:26:37.359Z",
  },
  {
    name: "Learn Low-Level-Design",
    description:
      "This course will provide you in depth knowledge of Low-Level-Design and this is the best course and there is high demand for this course.",
    duration: "3 Hour",
    image_url: "SystemDesign/lld.png",
    link: "https://www.geeksforgeeks.org/what-is-low-level-design-or-lld-learn-system-design/",
    topics: [
      "What is Low Level Design or LLD – Learn System Design",
      "Prerequisite OOPS Fundamentals",
      "SOLID Principle",
      "Design Patterns",
      "Problem on LLD",
    ],
    created_at: null,
    updated_at: null,
    deleted_at: "2025-11-12T23:28:31.882Z",
  },
  {
    name: "Learn Object-Oriented-Programming WITH C++",
    description:
      "This course will provide you in depth knowledge of Object-Oriented-Programming and this is the best course and there is high demand for this course.",
    duration: "3 Hour",
    image_url: "SystemDesign/oopswithc++.png",
    link: "https://www.w3schools.com/cpp/cpp_oop.asp",
    topics: [
      " C++ What is OOP?",
      "C++ Classes/Objects",
      "C++ Class Methods",
      "C++ Constructors",
      "C++ Access Specifiers",
      "C++ Encapsulation",
      "C++ Packages",
      "C++ Inheritance",
      "C++ Inner Classes",
      "C++ Abstraction",
      "C++ Interface",
    ],
    created_at: null,
    updated_at: null,
    deleted_at: "2025-11-12T23:28:54.898Z",
  },
  {
    name: "Learn Object-Oriented-Programming WITH Java",
    description:
      "This course will provide you in depth knowledge of Object-Oriented-Programming and this is the best course and there is high demand for this course.",
    duration: "3 Hour",
    image_url: "SystemDesign/oopswithjava.png",
    link: "https://www.w3schools.com/java/java_oop.asp",
    topics: [
      " What is OOP?",
      "Java Classes and Objects",
      "Java Class Attributes",
      "Java Constructors",
      "Java Modifiers",
      "Java Encapsulation",
      "Java Packages",
      "Java Inheritance",
      "Java Inner Classes",
      "Java Abstraction",
      "Java Interface",
    ],
    created_at: null,
    updated_at: null,
    deleted_at: "2025-11-12T23:28:56.723Z",
  },
  {
    name: "Learn Computer Network",
    description:
      "This course will provide you in depth knowledge of Computer Network and this is the best course and there is high demand for this course.",
    duration: "12",
    image_url: "CSFunda/cn.png",
    link: "https://www.geeksforgeeks.org/computer-network-tutorials/",
    topics: [
      "Basics of Computer Network",
      "Network Hardware and Software",
      "Network Topology",
      "OSI Mode",
      "Protocols",
      "TCP/IP Model",
      "Medium Access Control",
      "SLIDING WINDOW PROTOCOLS",
      "IP Addressing",
      "Routing",
      "Application Layer:DNS",
    ],
    created_at: null,
    updated_at: "2025-11-12T18:41:09.599Z",
    deleted_at: null,
  },
  {
    name: "Learn Computer Network",
    description:
      "This course will provide you in depth knowledge of Mangement System and this is the best course and there is high demand for this course.",
    duration: "3 Hour",
    image_url: "CSFunda/dbms.png",
    link: "https://www.geeksforgeeks.org/dbms/",
    topics: [
      "Basic of DBMS",
      "Entity Relationship Model",
      "Relational Model",
      "Relational Algebra",
      "Functional Dependencies",
      "Normalisation",
      "Transactions and Concurrency Control",
      "Indexing, B and B+ trees",
      "File organization",
    ],
    created_at: null,
    updated_at: "2025-11-12T18:40:38.933Z",
    deleted_at: null,
  },
  {
    name: "Learn PHP Core",
    description:
      "This course will provide you in depth knowledge of core PHP and this is the best course and there is high demand for this course.",
    duration: "12",
    image_url: "ProgLang/php.png",
    link: "https://www.w3schools.com/php/",
    topics: [
      "PHP Home",
      "PHP Install",
      "PHP Syntax",
      "PHP Comments",
      "PHP Variables",
      "PHP Echo/Print",
      "PHP Datatype",
      "PHP String",
      "PHP Numbers",
      "PHP Casting",
      "PHP Math",
      "PHP Constraint",
      "PHP Magic Constraint",
      "PHP Operators",
      "PHP If...Else...Elseif",
      "PHP Switch",
      "PHP Loops",
      "PHP Functions",
      "PHP Arrays",
      "PHP Superglobals",
      "PHP RegEx",
    ],
    created_at: null,
    updated_at: "2025-11-12T18:42:16.563Z",
    deleted_at: null,
  },
  {
    name: "Learn Operating System",
    description:
      "This course will provide you in depth knowledge of Operating System and this is the best course and there is high demand for this course.",
    duration: "4 Hour",
    image_url: "CSFunda/os.png",
    link: "https://www.geeksforgeeks.org/operating-systems/",
    topics: [
      "What is an Operating System?",
      "What is an Operating System Used for?",
      "Functions of the Operating System",
      "Objectives of Operating Systems",
      "Types of Operating Systems",
      "How to Choose the Operating System?",
    ],
    created_at: null,
    updated_at: "2025-11-12T18:45:24.155Z",
    deleted_at: null,
  },
  {
    name: "Learn Core C",
    description:
      "This course will provide you in depth knowledge of core C++ and this is the best course and there is high demand for this course.",
    duration: "3 Hour",
    image_url: "ProgLang/c++.png",
    link: "https://www.w3schools.com/php/",
    topics: [
      "C++ Home",
      "C++ Install",
      "C++ Syntax",
      "C++ Comments",
      "C++ Variables",
      "C++ Echo/Print",
      "C++ Datatype",
      "C++ String",
      "C++ Numbers",
      "C++ Casting",
      "C++ Math",
      "C++ Constraint",
      "C++ Magic Constraint",
      "C++ Operators",
      "C++ If...Else...Elseif",
      "C++ Switch",
      "C++ Loops",
      "C++ Functions",
      "C++ Arrays",
      "C++ Superglobals",
      "C++ RegEx",
    ],
    created_at: null,
    updated_at: "2025-11-12T18:45:45.192Z",
    deleted_at: null,
  },
  {
    name: "Learn Core C",
    description:
      "This course will provide you in depth knowledge of core C and this is the best course and there is high demand for this course.",
    duration: "3 Hour",
    image_url: "ProgLang/c.png",
    link: "https://www.w3schools.com/php/",
    topics: [
      "C Home",
      "C Install",
      "C Syntax",
      "C Comments",
      "C Variables",
      "C Echo/Print",
      "C Datatype",
      "C String",
      "C Numbers",
      "C Casting",
      "C Math",
      "C Constraint",
      "C Magic Constraint",
      "C Operators",
      "C If...Else...Elseif",
      "C Switch",
      "C Loops",
      "C Functions",
      "C Arrays",
      "C Superglobals",
      "C RegEx",
    ],
    created_at: null,
    updated_at: "2025-11-12T18:46:47.675Z",
    deleted_at: null,
  },
  {
    name: "Learn Core Python",
    description:
      "This course will provide you in depth knowledge of core python and this is the best course and there is high demand for this course.",
    duration: "3 Hour",
    image_url: "ProgLang/python.png",
    link: "https://www.w3schools.com/php/",
    topics: [
      "Python Home",
      "Python Install",
      "Python Syntax",
      "Python Comments",
      "Python Variables",
      "Python Echo/Print",
      "Python Datatype",
      "Python String",
      "Python Numbers",
      "Python Casting",
      "Python Math",
      "Python Constraint",
      "Python Magic Constraint",
      "Python Operators",
      "Python If...Else...Elseif",
      "Python Switch",
      "Python Loops",
      "Python Functions",
      "Python Arrays",
      "Python Superglobals",
      "Python RegEx",
    ],
    created_at: null,
    updated_at: "2025-11-12T18:49:25.191Z",
    deleted_at: null,
  },
];
export const rolesData = [{ name: "User" }, { name: "Admin" }];
